### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fbausch** [MarkusH/pxchat#1]
We need a license because the code is public readable.

**Comment by fbausch** [comment]
Possible licenses:
BSD
MPL
CC-BY-NC-SA

(see Wikipedia for more information)

**Comment by rwaury** [comment]
What about a BSD style license?

**Comment by fbausch** [comment]
The question is, if we want to allow commercial use.

I would prefer CC-BY-NC-SA.

**Comment by fbausch** [comment]
We could also take a CC-BY-SA license, but I think we should take CC-BY-NC-SA.

**Comment by MarkusH** [comment]
No-Commercial should be added first, but can be removed later

**Comment by rwaury** [comment]
Why prohibit commercial use?

**Comment by fbausch** [comment]
The probability that somebody will use it commercially is very low. But we can first block it and later allow it. CC-BY-NC-SA would be the easiest way for this.

**Comment by alexthewolf** [comment]
i think this sounds good.
so my choice would be cc-by-nc-sa as well.

**Comment by MarkusH** [comment]
Since one. abstains from that discussion, three votes pro CC-BY-NC-SA and one contra, the license is CC-BY-NC-SA (more information at http://creativecommons.org/licenses/by-nc-sa/3.0/)

**Comment by MarkusH** [comment]
Fixed in 72c221316dfa8f86a22fedd882795fdd0d1890d1
