### ISSUE TITLE
Lock/Unlock

### ISSUE THREAD

**Issue by MarkusH** [MarkusH/pxchat#10]
when the whiteboard locking owner disconnects, the server is inforced to unlock the whiteboard. Additionally the locking status must be send to newly created connections

**Comment by rwaury** [comment]
second part is solved by 33a820380e436f65be5a5698b1cf25703b070e1e

**Comment by rwaury** [comment]
first part
11276bc65e76f09c18b93b55b6cdd6026f2009d6
