### ISSUE TITLE
send Background image to new connections

### ISSUE THREAD

**Issue by MarkusH** [MarkusH/pxchat#11]
when a new connection is established, the current background image has to be send.

**Comment by markusd** [comment]
Send images to clients connected 1) after the image was sent 2) during the transfer process. Added functionality to ImageClear Button. Fixed bug that caused wrong authentications to raise an NullPointerException on the server while trying to send a LockFrame.

Closed by 1c62bafcea44e08fc0fd61e654c79ef7f280be48
