### ISSUE TITLE
Bug in Free Hand drawing tool

### ISSUE THREAD

**Issue by rwaury** [MarkusH/pxchat#15]
When I started drawing with the free hand tool on the whiteboard the session was disconnected.

If you draw other stuff beforehand the bug doesn't occur.

Test system was Ubuntu Linux.

**Comment by markusd** [comment]
I suggest to cache the drawing on the client for a few milliseconds. The data is then sent as a single Frame to the server. This should improve the performance and avoid deadlocks.

I will try to fix this the next days.

**Comment by markusd** [comment]
Added caching of FreeHand Tool and Eraser (which is the FreeHand Tool with the color [0, 0, 0, 0]). Cleaned up and commented code.

Closed by a1479b600ec0122539943196944f40dabeb5ff06
