### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by markusd** [MarkusH/pxchat#3]
There are some issues with the ResourceBundle; it only supports ISO 8859-1 which is rather ridiculous. There 3 are possibilities:

1) Don't do anything and do not use or escape all special characters with \u...

2) Do some Quick'n'Dirty stuff which does not really work so well as described here: http://www.thoughtsabout.net/blog/archives/000044.html

3) Use XML property files; an approach is described here: http://bordet.blogspot.com/2007/01/utf-8-handling-for-resourcebundle-and.html

**Comment by MarkusH** [comment]
In my opinion escaping each character is more than dirty. And as titled, the 2) is dirty too. Obviously XML property files would be the best.

**Comment by markusd** [comment]
Drawback is that we need JDK 5/6 for that; but that should not be too bad. Did we even mention a JVM in our functional specification?

**Comment by MarkusH** [comment]
Yes, we specified JDK 1.6 which is equal to Java 6.

**Comment by fbausch** [comment]
I think escaping special characters is not a big problem.
You only need some lines of JavaScript code that displays you the escaped special characters. (I already wrote such a short script, but I have to look for it on my HDD.)
I think the ratio of use and effort is the best with this approach.

**Comment by rwaury** [comment]
Since we are already knee-deep in the XML swamp I'm also in favor of option 3.

**Comment by alexthewolf** [comment]
the xml thing sounds nice. I would prefer this as well if it's not to much extra work.
but that should be fine as we got enough time ;-)

**Comment by MarkusH** [comment]
Ok. I delegate the work to alexthewolf. We use XML based property files.

**Comment by fbausch** [comment]
Improved German i18n. closed by d78c94ae58c37e12891d770e0c34e990a294c73d
