### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by MarkusH** [MarkusH/pxchat#4]
As you can see in bfd14e203d8e0952190e8d4e76e30f43684e2cbf , there are lots of modifications because of inconsistent formatting rules. To avoid this in future please import doc/eclipse-formatting.xml to your eclipse settings. For a short howto have a look at the commit message at 7060d474c979d38259c9a8bfd67a2aba6ea20edc

**Comment by markusd** [comment]
Done. Unfortunately you did that while I made some changes too... Had to merge everything :-(

**Comment by MarkusH** [comment]
Sorry for that.
