### ISSUE TITLE
Choose port

### ISSUE THREAD

**Issue by fbausch** [MarkusH/pxchat#6]
We need a port where the server is listening on respectively the client sends on.

**Comment by markusd** [comment]
I'm voting for port 16241. (px! --> 16 = p, 24 = x, 1 = !)

**Comment by MarkusH** [comment]
You are crazy. But finally I don't care.

**Comment by rwaury** [comment]
How can any sane human being miss the most obvious answer to that question? The best choice is of course 4242. 
You are welcome ;-)

**Comment by markusd** [comment]
You failed, Robert! When making such a ridiculous proposal you should at least verify that this port is not used by other applications. Search for it in Google and you will find multiple entries for that. Did I already mention that you failed spectacularly?

**Comment by fbausch** [comment]
You all failed! xD

We take 2011.

**Comment by rwaury** [comment]
I can only find entries of it being used for malware, connectix videophone, a service called payline, multi-user dungeons and an IBM AIX vulnerability. 
If one of you had ever used any of this applications prior to this day I will gladly reconsider my awesome proposal.
Again, you are welcome.

P.S.: Markus, this pathetic attempt to insult me will not be without consequences ;-)

P.P.S.: Exaggeration Fail

**Comment by markusd** [comment]
I demand satisfaction! Tomorrow, 10:45. Choice of weapons is yours. I would suggest verbal bashing.

P.S.: How dare you close this issue?

**Comment by rwaury** [comment]
I admit closing this issue was rather bold of me.
But since 4242 is the only reasonable answer to this question it should be closed.

P.S.: Verbal bashing is fine since you never were very skilled with the usage of language.

P.P.S.: If you want to start the bashing now, the P.S. counts

**Comment by markusd** [comment]
I want to have this conversation face to face.

P.S.: My expertise in speaking eloquently is unreachable, even by you.

P.P.S.: Does anyone ever use a PPS without being obnoxious?

P.P.P.S.: I'm not impressed by your cowardice. At all.

**Comment by alexthewolf** [comment]
yeah flame.... :)

p.s.: i dont care as long as it works

p.p.s.: but the 16241 thing sounds very 1337

p.p.p.s.: who startet this p18s thing?

**Comment by rwaury** [comment]
Alex at the very first let me point out that you failed.
Furthermore, I would like to ask you to STFU and GTFO.

I may now leave you to a session of contemplation and self-criticism.

P.S.: WTF is p18s supposed to mean, dipshit?

P.P.S.: Looking forward to NOT hear from you. Ever.

**Comment by alexthewolf** [comment]
fail^^

**Comment by markusd** [comment]
I suggest you go into yourself and reconsider your unsatisfactory comment.

P.S.: Robert, I think he missed the most important point of this conversation.

**Comment by rwaury** [comment]
Since you obviously missed the invention of capitalization I again kindly ask you to GTFO.

P.S.: What part of "Ever" was unclear to you?

P.P.S.: At least you didn't invent additional (and incomprehensible) acronyms.

**Comment by fbausch** [comment]
Please read this important announcement of me to you all:
http://bit.ly/9jn5NB

**Comment by markusd** [comment]
Cool story, bro.

P.S.: Alex, I'm disappointed in your lack of participation in this world-shattering topic. 

P.P.S.: I trust you know what depends on the success of this mission.

**Comment by fbausch** [comment]
<°)))o><

**Comment by rwaury** [comment]
It is sad that Markus has to remind all of you that the choice of the port number is paramount for the success of this endeavour. Neglecting this discussion is equivalent to abandoning the project completely.
Therefore I ask you to get your shit together and make constructive contributions to this thread.

P.S.: Participate, retards!

P.P.S.: @fbausch nobody cares about your links

**Comment by fbausch** [comment]
My suggestion: 2011

P.S.: OMG, WTF, GTFO, STFU!!!111einelf

**Comment by fbausch** [comment]
http://bit.ly/fL1aJa
