### ISSUE TITLE
Icons and Cursors

### ISSUE THREAD

**Issue by markusd** [MarkusH/pxchat#7]
We need some additional images:

1) An icon for the "Change background to color" button
2) Cursors for the following tools:
- Free hand
- Eraser

Maybe some cursors for the other tools would be neat, too.

**Comment by MarkusH** [comment]
partially fixed in 6018b5da10433d3e56e1777bebde3c23f9649d54

Cursors still needed.

**Comment by MarkusH** [comment]
fixed in ???
